steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/test-wordpress:v1", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/test-wordpress:v1"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - apply
  - --filename=k8s/deployment.yaml
  - --location=$_GKE_LOCATION
  - --cluster=$_GKE_CLUSTER
  # expose wordpress using k8s service
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - apply
  - --filename=k8s/svc.yaml
  - --location=$_GKE_LOCATION
  - --cluster=$_GKE_CLUSTER

