kind: Deployment
apiVersion: apps/v1
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - name: wordpress
        image: gcr.io/level-calculus-268016/test-saishma-wordpress:v1
        imagePullPolicy: Always
        ports:
        - name: wordpress
          containerPort: 80
